path: /Users/ygao/Documents/alexandria/RUG/ml/DLpractical/task1/Task_1/yolo_synthetic_line_pretrain
train: images/train
val: images/val
test: images/test

name:
  0: Alef
  1: Ayin
  2: Bet
  3: Dalet
  4: Gimel
  5: He
  6: Het
  7: Kaf
  8: Kaf-final
  9: Lamed
  10: Mem
  11: Mem-medial
  12: Nun-final
  13: Nun-medial
  14: Pe
  15: Pe-final
  16: Qof
  17: Resh
  18: Samekh
  19: Shin
  20: Taw
  21: Tet
  22: Tsadi-final
  23: Tsadi-medial
  24: Waw
  25: Yod
  26: Zayin

nc: 27